#!/usr/bin/env python
import sys
import os
from home_api_app import App
import logging.config

if __name__ == '__main__':
    logging.config.fileConfig(os.path.join(os.path.dirname(os.path.realpath(__file__)),'home_api_logging.conf'))

    settings = {
        # Flask settings
        "FLASK_SERVER_NAME": 'localhost:8888',
        "FLASK_DEBUG": True,  # Do not use debug mode in production

        # Flask-Restplus settings
        "RESTPLUS_SWAGGER_UI_DOC_EXPANSION": 'list',
        "RESTPLUS_VALIDATE": True,
        "RESTPLUS_MASK_SWAGGER": False,
        "RESTPLUS_ERROR_404_HELP": False
    }

    app = App(settings=settings)
    sys.exit(app.start())
