#!/usr/bin/env python
import sys
import os
from home_api_app import App
import logging.config
import argparse
import socket

if __name__ == '__main__':
    logging.config.fileConfig(os.path.join(os.path.dirname(os.path.realpath(__file__)),'home_api_logging.conf'))

    current_hostname = socket.gethostbyname(socket.gethostname())

    parser = argparse.ArgumentParser(description='Start Home API')
    parser.add_argument('--host',
                        dest='host',
                        required=False,
                        default=current_hostname,
                        help='hostname of the server')

    parser.add_argument('--port',
                        dest='port',
                        required=False,
                        default=8887,
                        help='port of the server')

    parser.add_argument('--debug',
                        dest='debug',
                        required=False,
                        default=False,
                        help='debug mode')

    args = parser.parse_args()

    settings = {
        # Flask settings
        "FLASK_SERVER_NAME": '{0}:{1}'.format(args.host, args.port),
        "FLASK_DEBUG": args.debug,  # Do not use debug mode in production

        # Flask-Restplus settings
        "RESTPLUS_SWAGGER_UI_DOC_EXPANSION": 'list',
        "RESTPLUS_VALIDATE": True,
        "RESTPLUS_MASK_SWAGGER": False,
        "RESTPLUS_ERROR_404_HELP": False
    }

    app = App(settings=settings)
    sys.exit(app.start())
